#!/command/with-contenv sh

echo "Starting M172DMR"

# if missing, download the latest dmrid.dat from the XLXAPI server to the config dir
[ ! -f ${M172DMR_CONFIG_DIR}/DMRIDs.dat ] && echo "Downloading DMRIDs.dat" && curl -L -s -o ${M172DMR_CONFIG_DIR}/DMRIDs.dat http://xlxapi.rlx.lu/api/exportdmr.php

# if missing, download the latest XLXHosts.txt from the pistar server to the config dir
[ ! -f ${M172DMR_CONFIG_DIR}/XLXHosts.txt ] && echo "Downloading XLXHosts.txt" && curl -L -s -o ${M172DMR_CONFIG_DIR}/XLXHosts.txt https://www.pistar.uk/downloads/XLXHosts.txt

# start daemon
exec /usr/local/bin/M172DMR
